### ISSUE TITLE
browser can't decompress 

### ISSUE THREAD

**Issue by saiqulhaq** [Shopify/cacheable#37]
this gem was working fine, I was using this gem few months ago

but now I am getting this error:

![image](https://user-images.githubusercontent.com/1275215/71154963-5326fe00-226f-11ea-9828-84af5c335c39.png)

it's like the body is dumped, but not rendered correctly on browser side
I have tried few times to call `render` method in `response_cache`'s block argument

**Comment by rafaelfranca** [comment]
What changed between now and a few months ago that made this issue start to occur? Have you upgraded the gem? If, yes, from which commit to what commit?

How can we reproduce the issue?

**Comment by saiqulhaq** [comment]
if have another rails 6 app that using this gem since beginning, and have no issue

maybe the issue is because Redis
my old app that uses Rails 5 and Redis has this issue

it looks like Shopify support Memcached only 

I use  IdentityCache gem too, and it supports Memcached only

**Comment by saiqulhaq** [comment]
I've reading the source code, but still can't resolve this issue

finally today I create a controller concern that use same logic as this gem, but it's slower
because it's not in middleware level
